topic_name: education_topic
dataset: acs/acs5
year: 2022
variable_groups:
  b99151:
    label: Allocation of Educational Attainment for the Population 25 Years and Over
    variables:
    - B99151_001E
    - B99151_002E
    - B99151_003E
    - NAME
